### ISSUE TITLE
Excluding Categories List?

### ISSUE THREAD

**Issue by leejk421** [allejok96/jw-scripts#13]
Hello,

If this obvious I apologize, but I'd like to exclude a few categories from download, but not sure what the category list is. Is the list the same as the directory structure created on the filesystem, or something else? Perhaps if the --exclude argument is passed with no parameter, it could return a valid category list?

**Comment by allejok96** [comment]
Thanks for the feedback! It's not obvious because I don't know how to explain it with few enough words. The categories are the "codenames" you see at the beginning when running the script, like VODStudio or ChildrenFeatured. Since this is shown every time I see no need to make a separate function to display the list. Perhaps I will put some better explanation in the help message. Or at least in the wiki pages here on github...

**Comment by leejk421** [comment]
hmm... ok. When I issue this command, it just shows the current file downloading:

jwb-index --latest --download --mode filesystem --free 1 /Volumes/jw_broadcasting/videos
free space: 925 MiB, minimum limit: 1 MiB
LatestVideos (Latest Videos)
downloading: 502017872_E_cnt_1_r720P.mp4 (Think Past the Drink)

**Comment by allejok96** [comment]
I don't know exactly what you are trying to do... Please have a look at the wiki pages here on github, hope that can shed some light on it :
https://github.com/allejok96/jw-scripts/wiki/jwb-index

Seems to me like everything works as intended. The script downloads the files one by one...

**Comment by leejk421** [comment]
OK thank you. Using the url on tv.jw.org I was able to figure out the category names. In my previous post, I just meant that the category names were not output to the terminal when I ran the command as shown, but that's ok.

**Comment by allejok96** [comment]
Aha I see. The category name in your case is actually LatestVideos because --latest is simply a shortcut for --category LatestVideos.
