### ISSUE TITLE
Generate and Apply File Properties for Better Usability in Plex

### ISSUE THREAD

**Issue by sergebenard** [allejok96/jw-scripts#18]
Hello! I love what you've done with this project.

I would love to help create a dedicated Plex mode, to enable better listing and ease of use.

Please e-mail at serge.benard@gmail.com

**Comment by allejok96** [comment]
I'm glad you are willing to assist, because I don't have much time atm to work on some relatively big thing like this.

What are you aiming for when you say better listing and ease of use? Let me hear your outline.

I have very little insight on Plex myself. Never used it, so I don't know what the current condition of this script is. As far as I can understand there are only three ways to have media in Plex: through a dedicated add-on or "channel", through having Plex automatically scan for local media like series and movies, or through browsing manually in the filesystem.

**Comment by sergebenard** [comment]
Hello! I am so very happy you answered my message.

I am assigned to the Mountainview congregation, in Gatineau, Quebec, Canada.

I would LOVE to create new functionality for your terrific plugin.

Please visit the following document; it explains this in more detail and
it's easier to navigate than what an email reply could ever do.

https://docs.google.com/document/d/1IO-Vkudazmf8HeaN3JY1iEkNqrGSUMXr7z06X5iTloE/edit?usp=sharing

Looking forward to hearing from you again.

Serge
_________________________________
Please reply to serge.benard@gmail.com

**Comment by allejok96** [comment]
Ok, so it seems like there's not much more to do here, so I'm closing this issue.

Just to provide some context: The default ID3 tags on the videos from jw.org seems to be quite a mess, and when Plex scans them it think there are more collections or categories of videos then there really are. As it would be a major pain to try to re-tag all videos after downloading, the best solution is just to deactivate this function in Plex, and browse the videos as a normal file structure.

At least this is my understanding of it. So for now I say, problem solved.

Thanks for taking the time to straighten this out, Serge.
