### ISSUE TITLE
Lyrics and lead sheets

### ISSUE THREAD

**Issue by vknya** [allejok96/jw-scripts#24]
Hi Alex i want to download all original songs videos at one go with the following options:
 - language
 - subtitles (and select the language , when more than one is available) 
 i would also need to the program to find all resources coming with the song(lead sheet,lyrics,and video) and be able to download them in the specified language

**Comment by allejok96** [comment]
Hi brother! I've been looking into this. It is not that simple, since the site does not provide any way to easily get links to the lead sheets and lyrics, like it does with videos, recordings and publications.

Videos. The music videos can as you probably know be downloaded through `--category VODOriginalSongs`

Lyrics. This is trickier. Some music videos have external subtitles, and that is essentially the lyrics, but the older songs doesn't have these. Downloading external subtitles is a feature that I will add sometime in the future, @vbastianpc have kindly worked this out already, so you can check out his fork if you want to try it out.

Lead sheets. There is no good method of getting hold of the lead sheets. It would have to involve a HTML scrapper, which could easily be broken by any future changes in the website. Another con is that scrapping text and images from the website is prohibited by the terms of use.

So it looks like I won't be adding this feature any time soon. One thing you could do though is press Ctrl+S in the browser (like Firefox) and it will download the whole page, including lead sheets, video and HTML. I don't know if that is any easier than manually downloading the things you want....
