### ISSUE TITLE
JW Broadcasting video bug

### ISSUE THREAD

**Issue by marek-dziechciarz** [allejok96/jw-scripts#26]
You did good job with this app.
But i got a bug with video.
I use Xiaomi Mi Box S with Android TV 9.
First this bug i solved with factory reset.
But this is not a solution if i must factory reset even couple days.
Audio files work fine.

Plz. Fix this bug.

**Comment by marek-dziechciarz** [comment]
![Uploading 20200215_184843.jpg…]()

**Comment by marek-dziechciarz** [comment]
This bug also found on TCL Android TV

**Comment by allejok96** [comment]
You have to describe what you are doing and be more specific about what's not working before I can offer any help. Are you downloading videos with the script on you computer and transferring them to your Android box? What's wrong with the video? I can't fix a bug if I don't know what it is...

**Comment by marek-dziechciarz** [comment]
Hi
You probably answer to me to an e-mail with information about the clue of the bug is the newest update of Android Web View is incompatible with ATV 9 especially od Mi Box

**Comment by allejok96** [comment]
I want to help you, but it feels like there is not so much I can do.

The software here called jwb-index only downloads videos from jw.org. You can verify this by downloading a video from jw.org the normal way (using a web browser) and trying to play that video on the Mi box. If you still only have sound, then the bug is in Android and not in this software.

If the bug is not in my code, I can't fix it.

 That's my assumption. It could be different, but you haven't told me _how_ you actually use jwb-index.

**Comment by allejok96** [comment]
Closing due to lack of info
