### ISSUE TITLE
Windows: link not working

### ISSUE THREAD

**Issue by roffikk** [allejok96/jw-scripts#31]
Hey. I've installed your scripts successfully on Windows 10, but links aren't working. Specifically, the ones that are inside localized folders. If I right-click them, I see they point to e.g. "C:\JWB\Dzieci\pkon_P_017_r720.mp4", while they should point to "C:\JWB\jwb-P\pkon_P_017_r720.mp4". Links that are inside "C:\JWB\jwb-P\BJF" are working perfectly (although they got no thumbnail). I understand that they are hard links, right? Maybe if your script generate symbolic links, they would be fine?...

**Comment by allejok96** [comment]
It could be that this has never worked on windows...

I guess the problem is how windows interprets nested symbolic links. Yes they are symbolic, but probably explorer shows you the real path when you right click the link (try moving the link, and the path should change).

I'm trying to think of a not so complicated solution...

**Comment by roffikk** [comment]
Ok, bummer. I mistaken hard links for symbolic links. Interesting fact: if I copy a file to a different folder, it has a nice thumbnail and it works, no matter if it was in localized folder or the one with category name. Copying either file or the folder copies physical file or files. So yes, it seems that link to a folder is the only issue.

How about link files (*.lnk)?

**Comment by allejok96** [comment]
Good to know windows copies the real files when copying a symlink... I think the issue is fixed now, using absolute paths.
