### ISSUE TITLE
new approach 

### ISSUE THREAD

**Issue by jw-in-1-Team** [allejok96/jw-scripts#34]
hello, my brother, 

congratulations on your script, I want to ask for authorization to use JW-stream in our GitHub that we develop, and I search a way to have the monthly broadcasting. 

I will be happy if you want to contact us for a synergy job. 

Brother love.

**Comment by allejok96** [comment]
Hi! I'm very impressed with your work. Quite clever to use google docs to manage the settings too. You have my permission. Go ahead and use jw-stream. Don't be afraid to give me feedback if there is something you need or if you discover any bugs. I'm afraid I won't be of much help otherwise, since I do not own a Windows computer. So I can't test your awesome software (although you've got me really curious).

Here's a few other things you might find interesting:

- jwb-index can stash a fixed amount of videos on the hard drive and keep it updated, using the `--free` flag. It's useful if the HDD is large and they want to save bandwidth.

- [SikuliX](http://sikulix.com/) is a monstrous program. I had a computer setup to connect to a local SIP phone service that we had here in Sweden, and then call into Zoom as a virtual user. And SikuliX would handle raise hand automatically and rename the user to whoever was speaking. It was extremely hacky and eats CPU and likes to get stuck whenever unknown dialog boxes pop up... but it's so cool.

- I checked out your website. And saw some notes on "allow unmute". I guess you already know about the new "always allow unmute" permission that Zoom has... It makes life so much easier.
