### ISSUE TITLE
Improving streaming

### ISSUE THREAD

**Issue by jw-in-1-Team** [allejok96/jw-scripts#36]
hello, thanks for all you comment in previous issues: 

if i run python "jwb-stream" --lang F --category VODOurOrganization,VODStudio,VODOurActivities,VODIntExp,VODFamily,VODChildren,VODFamily "C:\Program Files\VideoLAN\VLC\vlc.exe"  --fullscreen --video-on-top --sub-autodetect-file
the vlc need to be close the same number of category... can we change to close only one time VLC? 

and also is possible to have an argument in jw-stream --quiet to not see the print of indexing! 

thanks

**Comment by allejok96** [comment]
Hey I've pushed some new features to jwb-index, I think it will suit your needs better. There may be bugs.

`--mode=m3u_single` creates a single playlist from everything you specified
`--sort=date` does what you think it does
`--append` adds new stuff to the playlist instead of overwriting it
`--filename=NAME` is the name of the playlist, default name is "output" (.m3u will be added automatically)

Run this one time to create a playlist of all videos:

    jwb-index -m m3u_single --sort=date

And then run periodically, to add new videos to the playlist:

    jwb-index -m m3u_single --latest --append

Then start playing with:

    vlc --random output.m3u

**Comment by jw-in-1-Team** [comment]
hello, this is perfect, but for the --sort=date  i don't have in the right order can you do also the option --sort=datereverse ? 

i need the newest first ! 

thanks by advance

**Comment by jw-in-1-Team** [comment]
this is very strange, i try with --category VODMovies
and recreate the file mu3 all the time, but the list is not the same size: 1 time 18 movies, 1 time 29 movies !!!! 
this is very STRANGE !!! can you have a look ! 

thanks so much

**Comment by allejok96** [comment]
Can you please write the exact command you ran?

**Comment by jw-in-1-Team** [comment]
thanks to ask me .... that was the right question !!! what a pleasure to work with you !!!!  my script generated a double \\

before make trouble call python "jw-scripts-master\\jwb-index" -m m3u_single  --sort=random --lang F --category VODMovies

no trouble NOW  call python "jw-scripts-master\jwb-index" -m m3u_single  --sort=random --lang F --category VODMovies

thanks i will update when the project jw-in-1 will be ready and you can test it!

**Comment by jw-in-1-Team** [comment]
but for the --sort=date i don't have in the right order can you do also the option --sort=datereverse ?

i need the newest first !

thanks by advance

**Comment by jw-in-1-Team** [comment]
that should be nice we can change the name of the file out output.m3u ... because we can prepare different list

**Comment by allejok96** [comment]
I've done some major rework to the output writing code. Also modes have new names. Will update the wiki soon.

Now you can do

    jwb-index -c VODChildren --sort newest -m m3u path/to/folder/children.m3u
    vlc path/to/folder/children.m3u

You should be able to do this, to keep adding new videos to a playlist (but I need to test this more, probably full of bugs)

    jwb-index -c LatestVideos --append --sort newest -m m3u path/to/folder/all_videos.m3u

Jwb-stream is gone, if you want that functionality

    jwb-index --mode run vlc

But it is better to save to a playlist, then open that with vlc, otherwise it will need to download and index the categories every time.

Please play around and tell me about the things that are broken :)

**Comment by jw-in-1-Team** [comment]
thanks so much, i agree i won't use --append, 
but i try to use the new some problem with the path 

jw-in-1-src>call python "jw-scripts-master\jwb-index"  --sort newest --lang F --category LatestVideos  -m m3u ../output.m3u
note: NTFS/FAT compatibility is off
indexing: LatestVideos (Nouveautés)
writing: ..\output.m3u

first i want to write in the same folder , but don't write, i add ../ but nothing

**Comment by jw-in-1-Team** [comment]
i success to write on a folder level above or below. but impossible to write on the level where i launch the python

**Comment by allejok96** [comment]
Hey thanks for the patience, bug is fixed. Append should also be working.

**Comment by jw-in-1-Team** [comment]
yes thanks so much, our project is on line on GITHUB. and also we have a video in english in our [jw-in-1.com](https://www.jw-in-1.com/home) website. i hope you have time to test on a windows.
